FROM python:3.11-slim

WORKDIR /app

COPY pyproject.toml .
COPY LICENSE .
COPY README.md .
COPY src/ src/
COPY tools/ tools/

RUN pip install --no-cache-dir .[chaos]

ENV PYTHONUNBUFFERED=1

CMD ["python", "-m", "src.main_node"]
