apiVersion: v1
kind: Service
metadata:
  name: {{ include "synapse.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "synapse.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.dashboardPort }}
      targetPort: https
      protocol: TCP
      name: https
    - port: {{ .Values.service.meshPort }}
      targetPort: mesh
      protocol: TCP
      name: mesh
  selector:
    app.kubernetes.io/name: {{ include "synapse.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
