name: Continuous Integration

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  verify:
    name: Lint, Test, & Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0

      - name: Install dependencies
        run: |
          python -m venv .venv
          .venv/bin/pip install -e .[dev,chaos]

      - name: Run verification (Mypy, Ruff, Pytest, Helm)
        run: make verify


